export const OPTIONS_PAGE = "OPTIONS_PAGE";
export const ROUTE_DETAILS_PAGE = "ROUTE_DETAILS_PAGE";
export const REPORTING_PAGE = "REPORTING_PAGE";
export const ROUTE_ADDITIONAL_DETAILS = "ROUTE_ADDITIONAL_DETAILS";
export const VIEW_AND_CHANGE = "VIEW_AND_CHANGE";
export const SET_STARTING_AND_ENDING = "SET_STARTING_AND_ENDING";
