export const CURRENT_USER = { id: "123456" };

export const USERS = [
  {
    id: 1,
    lastName: "Snow",
    firstName: "Jon",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 2,
    lastName: "Lannister",
    firstName: "Cersei",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 3,
    lastName: "Lannister",
    firstName: "Jaime",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 4,
    lastName: "Stark",
    firstName: "Arya",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 5,
    lastName: "Targaryen",
    firstName: "Daenerys",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 6,
    lastName: "Melisandre",
    firstName: "l",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 7,
    lastName: "Clifford",
    firstName: "Ferrara",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 8,
    lastName: "Frances",
    firstName: "Rossini",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 9,
    lastName: "Roxie",
    firstName: "Harvey",
    username: "username",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
  {
    id: 10,
    lastName: "admin",
    firstName: "admin",
    username: "admin",
    email: "email@gmail.com",
    mobile: "0500008877",
    usertype: "Matak",
    organization: "matak",
  },
];
